### ISSUE TITLE
Question about the vizAtlas_Freq_Directional.R 

### ISSUE THREAD

**Issue by PBHsieh** [stanleyn/VoPo#4]
Thanks to the powerful tool of VoPo you developed, I can reproduce the tSNE plot coloring with differentiation score on my CyTOF data now. 

But I'm not sure about the plot, shown below left, I created it by using the vizAtlas_Freq_Directional.R is equal to the left of supplementary figure 7, shown below right?
![063AAAD3-42B0-4F2A-99AB-24E65FB71B71](https://user-images.githubusercontent.com/29281658/141817022-b62ebd14-8a45-4377-9edd-ed95850bdc32.png)

![DCD802C5-E4AA-4728-85C8-1F641235B0C7](https://user-images.githubusercontent.com/29281658/141817040-804b1789-8161-41c0-ad47-dad8df15f5aa.png)

If the vizAtlas_Freq_Directional.R script is used to plot the left figure of supplementary figure 7, does the positive value in the color key represent "Control", which is set as 0 in the classification?
![98C41A72-6DFD-4819-92F4-163D14987F3C](https://user-images.githubusercontent.com/29281658/141817163-9ebf4fb5-e0f4-4f74-9b85-1ebd2f12e529.png)

Cause I can't really understand the conversion of the Mathematical calculation in the vizAtlas_Freq_Directional.R script.

Thanks for your help.

**Comment by stanleyn** [comment]
Hi, thanks for providing your example.

Assuming you have mapped your labels to Control and Treatment as 0 and 1 respectively (so Control is 0 and 1 is treatment), then the **blue color** will imply higher in control and the **red color** will be higher in treatment. 

Basically what happens is that we calculate a sign as Mean(Frequencies from max label) - Mean(Frequencies from min Label). The control and MP example in the paper is a bit confusing because in that case the biologists had labeled the groups A and B where A was the treatment and B was the control. :)

**Comment by PBHsieh** [comment]
Thanks so much!
